# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vitor Sales
email: 
description:  <p>
  <img align="center" alt="Vitor-Javascript" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"/>
  <img align="center" alt="Vitor-Angular" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg"/>
  <img align="center" alt="Vitor-Node" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"/>
  <img align="center" alt="Vitor-Nestjs" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nestjs/nestjs-plain.svg"/>
  <img align="center" alt="Vitor-Css" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg"/>
  <img align="center" alt="Vitor-bootstrap" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg"/>
  <img align="center" alt="Vitor-Adonisjs" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/adonisjs/adonisjs-original.svg"/>
  <img align="center" alt="Vitor-docker" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"/>
  <img align="center" alt="Vitor-git" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"/>
  <img align="center" alt="Vitor-mongodb" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"/>
  <img align="center" alt="Vitor-php" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg"/>
  <img align="center" alt="Vitor-typescript" height="30" width="40" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"/>
</p>

### âš¡ Somos o que repetidamente fazemos. A excelÃªncia, portanto, nÃ£o Ã© um efeito, mas um hÃ¡bito. âš¡ ğŸ¤”
  <p>ğŸ”­ Atualmente na Rede D'or como Fullstack Developer</p>
  <p>ğŸŒ± Aprimorando atravÃ©s de projetos em Angular/Node</p>
  <p>ğŸ‘¯ Procuro colaborar ajudando iniciantes atravÃ©s de mentorias.</p>
  <p>ğŸ‘¾ Formado em Analise e Desenvolvimento de Sistemas</p>
  <p>ğŸ‘¾ Sistemas de InformaÃ§Ã£o</p>
  <p>ğŸ„ CertificaÃ§Ã£o SAFE</p>
  
  <p><img height="180em" src="https://github-readme-stats.vercel.app/api?username=Tvitor&show_icons=true&theme=dark"/><img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=andressansantos&layout=compact&theme=dark"/></p>

[![Linkedin](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/vitor-sales89/)
[![GITHUB](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white)](https://tvitor.github.io/)


baseurl: "https://tvitor.github.io/" # "/jekyll-wing-template" the subpath of your site, e.g. /blog
url: "https://tvitor.github.io/" # the base hostname & protocol for your site
github_username:  tvitor
# Build settings
markdown: kramdown
